"""Add juuyoudo column

Revision ID: 0411fe32f039
Revises: b6239c314fa8
Create Date: 2023-07-22 00:20:35.097886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0411fe32f039'
down_revision = 'b6239c314fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('juuyoudo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('juuyoudo')

    # ### end Alembic commands ###
