"""empty message

Revision ID: b6239c314fa8
Revises: cd4448dd4aee
Create Date: 2023-07-20 17:53:35.627864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6239c314fa8'
down_revision = 'cd4448dd4aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shinnkoudo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('shinnkoudo')

    # ### end Alembic commands ###
